### PR TITLE
`self.css_class` should be resolved in case it's a template variable

### PR DESCRIPTION
**Pull request by robi-richter**

### CODE REVIEW

**Comment by robi-richter** [comment]
@marteinn you are welcome. Any chance you'll update the pypi any time soon?
Thanks

**Comment by marteinn** [comment]
@robi-richter For sure, first thing tomorrow morning!

**Comment by marteinn** [comment]
@robi-richter There we go, should be up on pypi now

**Comment by robi-richter** [comment]
Thank you very much @marteinn

**Pull request merged**
