### PR TITLE
Use unit.patch to mock requests instead of responses

### LINKED ISSUE #34: Replace responses with unittest.mock in test suite

### PR DESCRIPTION
**Pull request by umr55766**
Fixes #34

### CODE REVIEW

**Comment by umr55766** [comment]
Hey @marteinn, am I on correct path ?

**Comment by marteinn** [comment]
@umr55766 Absolutely! I just took a quick glance and looks like a good way of replacing the responses library.  One thing is that your PR breaks on Py 3.5? https://travis-ci.org/Frojd/django-react-templatetags/jobs/537420202

**Comment by umr55766** [comment]
@marteinn I have fixed that issue and also mocked all the reference

**Comment by marteinn** [comment]
Awesome @umr55766, I will go through your PR:s when I get more time, so far, great work :)

**Comment by marteinn** [comment]
Looks good @umr55766, merging!

**Pull request merged**
